AllCops:
  Exclude:
    - '**/bin/*'
    - '**/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/SymbolArray:
  Exclude:
    - Rakefile

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
